name: Deploy static content to Pages

# Definindo quando esse fluxo será executado
on:
  # Quando houver um push na branch principal (main)
  push:
    branches: ["main"]

  # Também pode ser executado manualmente pela aba "Actions"
  workflow_dispatch:

# Permissões para o GitHub poder fazer o deploy no Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Garantindo que apenas um deploy ocorra por vez (sem cancelar o que já está em andamento)
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Job único de deploy
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest  # Rodar em máquina virtual com Ubuntu
    steps:
      # 1. Baixar meu repositório
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Preparar o Node.js (versão 16)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # 3. Instalar as dependências do projeto (npm install)
      - name: Instalar dependências
        run: npm install

      # 4. Rodar o ESLint para checar erros de código
      - name: Verificar código com ESLint
        run: npm run lint

      # 5. Configurar o ambiente para o GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # 6. Fazer o upload dos arquivos que serão publicados
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './src'  # Caminho da pasta que será publicada (mudar se for outra)

      # 7. Publicar o conteúdo no GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
